#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

ps aux --forest | awk '{print $1, $2, $3, $4, $5, $6, $8, $9, $10, $11}' | head -50
