#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop
# On the 9th iteration, it displays "Best School" and then "Hi" on a new line

counter=1

while [ "$counter" -le 10 ]
do
    if [ "$counter" -eq 4 ]; then
        echo "bad luck"
    elif [ "$counter" -eq 8 ]; then
	echo "good luck"
    else
        echo "Best School"
    fi

    ((counter++))
done
