#!/usr/bin/env bash
# This script displays different messages based on the loop iteration using a while loop and case statement

counter=1

# Using a while loop to iterate from 1 to 10
while [ "$counter" -le 20 ]
do
    case $counter in
        4)
            echo "4"
	    echo "bad luck from China"
            ;;
        9)
            echo "9"
	    echo "bad luck from Japan"
            ;;
        17)
            echo "17"
	    echo "bad luck from Italy"
            ;;
         *) 
            echo $counter
            ;;
    esac

    ((counter++))
done
