#!/usr/bin/env bash
# This script displays the content of the current directory in a format similar to ls,
# showing only the part of the name after the first dash

for file in *; do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
        display_name=$(echo "$file" | cut -d'-' -f2-)

        stat --printf="%A %6s %y %n\n" "$file" | sed -e "s|$(pwd)/||" -e "s|$file|$display_name|"
    fi
done
